### ISSUE TITLE
Migrate figma designs to the new wazuh component library

### ISSUE THREAD

**Issue by matiasmoreno876** [wazuh/wui#1]
| Version | Source branch
| --- | --- |
| 1.x.x | master | 

### Description:
Currently, the[ elastic ui style library](https://elastic.github.io/eui/#/) is used to carry out the Wazuh Kibana App developments. 
Currently we need to build developments with more personalized components, for that reason we need to modify the wazuh wui (forked from elastic eui) library. Starting from the following designs [UI KIT WEB REBRANDING](https://www.figma.com/file/azjcCSsWPp6N3cTKXmDsKT/UI-KIT-WEB-REBRANDING?node-id=267%3A802)
 
#### Tasks: 

- [x] Analysis and research on the functioning of the elastic eui library.
- [x] Create the Wazuh light and dark themes.
- [x] Modify base colors following this design [UI KIT WEB REBRANDING](https://www.figma.com/file/azjcCSsWPp6N3cTKXmDsKT/UI-KIT-WEB-REBRANDING?node-id=267%3A802).
- [x] Modify border radius for all components.

#### Acceptance Criteria

- The theme name should be Wazuh Light and Wazuh Dark.
- In the documentation we should have an entry that allows us to see the applied styles.
- We should be able to see the color palette for both dark and light mode.
- We should be able to see the border radius applied.

**Comment by asteriscos** [comment]
### Base border radius in form controls and cards

![image](https://user-images.githubusercontent.com/9343732/133129541-8d1821b6-94e2-4751-9884-87bde0a9c6cd.png)

![image](https://user-images.githubusercontent.com/9343732/133129760-893e9620-059b-4c15-92b4-a65a48b659a9.png)

**Comment by asteriscos** [comment]
### Core colors

![image](https://user-images.githubusercontent.com/9343732/133129915-a7f8bf76-dea6-4315-9e99-b303f35b5e23.png)

![image](https://user-images.githubusercontent.com/9343732/133129946-c152031b-7866-4052-993a-faf3ccbef07b.png)

**Comment by matiasmoreno876** [comment]
> Theme selector
![image](https://user-images.githubusercontent.com/49887871/133143187-418d4bd5-a415-4ea9-9f63-0c9d4deed888.png)

**Comment by asteriscos** [comment]
### Compressed forms

![image](https://user-images.githubusercontent.com/9343732/133301482-a8653729-6070-4678-9cc0-01a2aab321e5.png)

**Comment by asteriscos** [comment]
### Fixed dark and light theme colors

![image](https://user-images.githubusercontent.com/9343732/133302098-963f79b6-0b7e-4bf9-95a3-1a4e9338036b.png)

![image](https://user-images.githubusercontent.com/9343732/133302139-860daecd-859a-40cf-be79-af2652343c68.png)

**Comment by matiasmoreno876** [comment]
> Compressed Form with `focus` border color

![image](https://user-images.githubusercontent.com/49887871/133501834-b9feff22-7b77-49ee-b1dc-b85bde7f2612.png)

**Comment by matiasmoreno876** [comment]
>  All Form controls with `focus` border color

![image](https://user-images.githubusercontent.com/49887871/133502000-92237757-d4e1-40de-ac6b-941fdf294f43.png)

**Comment by matiasmoreno876** [comment]
> Tabs witout backgroud-color 

![image](https://user-images.githubusercontent.com/49887871/133502188-f3447269-2053-4518-bd34-b65a40b1bb2f.png)

**Comment by matiasmoreno876** [comment]
> Data grit with border-radius 10px

![image](https://user-images.githubusercontent.com/49887871/133508308-a6555d83-017b-46d2-8aab-2b3cc831483e.png)
