### ISSUE TITLE
Implement Wazuh UI in Wazuh Dashboard

### ISSUE THREAD

**Issue by asteriscos** [wazuh/wui#3]
| Version | Source branch/tag
| --- | --- |
| 1.x.x |  [v29.3.2](https://github.com/wazuh/wui/tree/v29.3.2)| 

We are currently developing a library of Wazuh components (forked from elastic eui). We need to be able to compile said library and use it in the [Wazuh dashboard project](https://github.com/wazuh/wazuh-dashboard)

#### Tasks: 

- [x] Investigate the correct way to compile the library.
- [x] Upload the library to the NPM / Yarn repositories (as applicable)
- [x] Deploy the library in Wazuh Dashboard keeping the project working properly

#### Acceptance Criteria

- We should be able to compile the library.
- Upload library in NPM / Yarn (as applicable).
- Apply the changes in Wazuh Dashboard, keeping the correct working of the project.
- We should be able to see the applied Wazuh ui changes in Wazuh Dashboard

**Comment by matiasmoreno876** [comment]
Wazuh dashboard with Wazuh wui changes (Dark mode)

![image](https://user-images.githubusercontent.com/49887871/137209286-c2880b59-0138-4e9e-8750-19a3b8d23d67.png)

![image](https://user-images.githubusercontent.com/49887871/137209305-8d4faa1a-c66b-42e3-8b51-a9ce9f41d4f3.png)

![image](https://user-images.githubusercontent.com/49887871/137209384-7fef6920-9788-4b9c-8d65-39d7477ce13f.png)

![image](https://user-images.githubusercontent.com/49887871/137209530-ef75862c-481f-48e2-a89e-17d10a7c9587.png)


![Uploading image.png…]()
