### ISSUE TITLE
Create Wazuh Dashboard UI components

### ISSUE THREAD

**Issue by asteriscos** [wazuh/wui#4]
| Version | Source branch/tag
| --- | --- |
| 1.x.x |  [v29.3.2](https://github.com/wazuh/wui/tree/v29.3.2)| 

Currently, the [Elastic UI style library](https://elastic.github.io/eui/#/) is used for developing the Wazuh Kibana application.
We need to build developments with more custom components, for that reason we need to modify the wazuh wui library (forked from elastic eui). From the following designs [UI KIT WEB REBRANDING](https://www.figma.com/file/azjcCSsWPp6N3cTKXmDsKT/UI-KIT-WEB-REBRANDING?node-id=267%3A802).
Starting from tag [v29.3.2](https://github.com/wazuh/wui/tree/v29.3.2)
In order to have a migration to wazuh dashboard in a simpler way.

#### Tasks: 

- [x] Modify the Amsterdam light and dark themes.
- [x] Modify base colors following this design [UI KIT WEB REBRANDING](https://www.figma.com/file/azjcCSsWPp6N3cTKXmDsKT/UI-KIT-WEB-REBRANDING?node-id=267%3A802).
- [x] Migrate the changes that we consider from this [PR](https://github.com/wazuh/wui/pull/2)

#### Acceptance Criteria

- The theme name should be Wazuh Light and Wazuh Dark.
- In the documentation we should have an entry that allows us to see the applied styles.
- We should be able to see the color palette for both dark and light mode.
- We must start from the tag [v29.3.2](https://github.com/wazuh/wui/tree/v29.3.2)

**Comment by asteriscos** [comment]
#### Summary

- Changes made in this [PR](https://github.com/wazuh/wui/pull/2) applied to v29.3.2
- Replaced Amsterdam Light and Dark theme with Wazuh theme

![image](https://user-images.githubusercontent.com/9343732/135885712-ede9fe66-2fe4-4ca8-8c31-391fa2962f63.png)

**Comment by asteriscos** [comment]
Changing `Nav Drawer` features to show menu items according to its docker state.

![image](https://user-images.githubusercontent.com/9343732/136071412-31daf19b-0078-4679-8dd5-6e56adb96a2f.png)

**Comment by asteriscos** [comment]
#### Filtering in progress
![image](https://user-images.githubusercontent.com/9343732/136831243-b4876fb4-db0e-436f-83f2-8b8c7064b809.png)

**Comment by asteriscos** [comment]
#### Navigation and Advanced filtering prototype
![Peek 2021-10-13 18-53](https://user-images.githubusercontent.com/9343732/137178808-7aae6d94-9263-42a8-965a-d8539e3d2605.gif)

**Comment by asteriscos** [comment]
Changes made in **v29.3.2** were branched in [develop](https://github.com/wazuh/wui/tree/develop). Future issues will be merged in that branch.
